In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/Student_Performance.csv')

In [3]:
df.shape

(25000, 16)

In [4]:
df = df.dropna()

In [5]:
df.head()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f

In [6]:
df.shape

(25000, 16)

In [7]:
df = df.drop_duplicates(keep='first')

In [8]:
df.shape

(15000, 16)

Clean Text Columns

In [9]:
df['gender'] = df['gender'].str.strip().str.lower()
df['gender']

0          male
1        female
2        female
3         other
4        female
          ...
14995      male
14996     other
14997      male
14998     other
14999     other
Name: gender, Length: 15000, dtype: object

In [10]:
df['school_type'] = df['school_type'].str.strip().str.lower()
df['school_type']

0         public
1         public
2        private
3         public
4         public
          ...
14995    private
14996    private
14997    private
14998    private
14999     public
Name: school_type, Length: 15000, dtype: object

In [11]:
df['parent_education'].value_counts()

parent_education
diploma          2581
post graduate    2535
high school      2532
graduate         2481
no formal        2445
phd              2426
Name: count, dtype: int64

In [12]:
df['parent_education'] = df['parent_education'].str.strip().str.lower()
df['parent_education']

0        post graduate
1             graduate
2        post graduate
3          high school
4          high school
             ...
14995         graduate
14996          diploma
14997              phd
14998         graduate
14999        no formal
Name: parent_education, Length: 15000, dtype: object

In [13]:
df['travel_time'].value_counts()

travel_time
15-30 min    3823
30-60 min    3813
>60 min      3716
<15 min      3648
Name: count, dtype: int64

In [14]:
mapping = {
    '<15 min': 7.5,      # midpoint of 0-15
    '15-30 min': 22.5,   # midpoint of 15-30
    '30-60 min': 45,     # midpoint of 30-60
    '>60 min': 75        # assume average over 60
}

df['travel_time_min'] = df['travel_time'].map(mapping)
df['travel_time_min'].mean()

np.float64(37.5775)

In [15]:
df.head()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade,travel_time_min
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e,7.5
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d,75.0
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b,7.5
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e,22.5
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f,45.0

In [16]:
df['study_method'].value_counts()

study_method
mixed            2602
textbook         2546
notes            2515
online videos    2468
group study      2447
coaching         2422
Name: count, dtype: int64

In [17]:
df['final_grade'].value_counts()

final_grade
d    3770
c    3697
e    3378
f    1796
b    1638
a     721
Name: count, dtype: int64

In [18]:
df['final_grade'].unique()

array(['e', 'd', 'b', 'f', 'c', 'a'], dtype=object)

In [21]:
df['final_grade'] = pd.Categorical(
    df['final_grade'],
    categories=['f','e','d','c','b','a'],  # from lowest to highest
    ordered=True
)

In [20]:
df.to_csv('../data/processed/cleaned_data.csv', index=False)