In [56]:

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
import joblib

In [57]:
df = pd.read_csv('../data/processed/cleaned_data.csv')

Categorical Columns:

gender
- Gender is categorical
- One hot encoding
- No ordinal relationship exists between categories

In [58]:
df = pd.get_dummies(df, columns=['gender'], drop_first=True, dtype=int)

In [59]:
df.head()

,student_id,age,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade,travel_time_min,gender_male,gender_other
0,1,14,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e,7.5,1,0
1,2,18,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d,75.0,0,0
2,3,17,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b,7.5,0,0
3,4,16,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e,22.5,0,1
4,5,16,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f,45.0,0,0

school_type
- Only two categories, so it’s binary
- Map it to 0/1 directly

In [60]:
df['school_type_encoded'] = df['school_type'].map({'public':0,'private':1})

parent_education
- Categorical and ordinal column
- Ordinal encoding

In [61]:
education_order = [['no formal', 'high school', 'diploma', 'graduate', 'post graduate', 'phd']]
encoder = OrdinalEncoder(categories=education_order)

df['parent_education_encoded'] = encoder.fit_transform(df[['parent_education']])

study_hours
- Numerical Column

attendance_percentage
- Numerical column

internet_access
- Categoical & binary
- Map it to 0/1 directly

In [62]:
df['internet_access_encoded'] = df['internet_access'].map({'yes':1,'no':0})

extra_activities
- Categorical & binary column
- 0/1 encoding

In [63]:
df['extra_activities_encoding'] = df['extra_activities'].map({'yes':1,'no':0})

study_method
- Categorical & no order
- One hot encoding

In [65]:
df = pd.get_dummies(df,columns=['study_method'],drop_first=True,dtype=int)

In [66]:
df[df['student_id'] == 6]

,student_id,age,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,math_score,...,gender_other,school_type_encoded,parent_education_encoded,internet_access_encoded,extra_activities_encoding,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook
5,6,19,public,no formal,3.8,69.6,yes,>60 min,yes,51.5,...,0,0,0.0,1,1,0,0,0,0,0

final_grade
- categorical & ordinal
- label encoding

In [46]:
encoder = LabelEncoder()
df['final_grade_encoded'] = encoder.fit_transform(df['final_grade'])

In [47]:
df.head()

,student_id,age,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,math_score,...,school_type_encoded,parent_education_encoded,internet_access_encoded,extra_activities_encoding,study_method_group study,study_method_mixed,study_method_notes,study_method_online videos,study_method_textbook,final_grade_encoded
0,1,14,public,post graduate,3.1,84.3,yes,<15 min,yes,42.7,...,0,4.0,1,1,0,0,1,0,0,4
1,2,18,public,graduate,3.7,87.8,yes,>60 min,no,57.6,...,0,3.0,1,0,0,0,0,0,1,3
2,3,17,private,post graduate,7.9,65.5,no,<15 min,no,84.8,...,1,4.0,0,0,0,0,1,0,0,1
3,4,16,public,high school,1.1,58.1,no,15-30 min,no,44.4,...,0,1.0,0,0,0,0,1,0,0,4
4,5,16,public,high school,1.3,61.0,yes,30-60 min,yes,8.9,...,0,1.0,1,1,1,0,0,0,0,5

Drop Unnecessary Columns from the Dataset

In [48]:
df.drop(columns=['student_id','school_type','parent_education','internet_access','travel_time','extra_activities','final_grade'],inplace=True)

Rename columns

In [49]:
df.rename(columns={'study_method_group study': 'study_method_group_study'}, inplace=True)
df.rename(columns={'study_method_online videos': 'study_method_online_videos'}, inplace=True)

In [50]:
df.columns

Index(['age', 'study_hours', 'attendance_percentage', 'math_score',
       'science_score', 'english_score', 'overall_score', 'travel_time_min',
       'gender_male', 'gender_other', 'school_type_encoded',
       'parent_education_encoded', 'internet_access_encoded',
       'extra_activities_encoding', 'study_method_group_study',
       'study_method_mixed', 'study_method_notes',
       'study_method_online_videos', 'study_method_textbook',
       'final_grade_encoded'],
      dtype='object')

In [51]:
df.to_csv('../data/processed/preprocesses_data.csv',index=False)

Save Encoder to use while predicting result

In [52]:
joblib.dump(encoder, "../models/grade_encoder.pkl")

['../models/grade_encoder.pkl']